# Generated by Django 4.2 on 2023-04-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icons/%Y/%m/%d/'),
        ),
    ]
