# Generated by Django 4.2 on 2023-04-22 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_alter_goods_icon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
        migrations.RenameModel(
            old_name='Goods',
            new_name='Good',
        ),
    ]
